"""empty message

Revision ID: 0fffd8de635f
Revises: 824508dc1cb6
Create Date: 2021-08-07 00:23:23.517137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fffd8de635f'
down_revision = '824508dc1cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('show', 'showTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('showTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
